(ns groq_lpu.actor
  "groq_lpu clean-room actor — Clojure over the kotoba Datom log (EAVT, Datomic-isomorphic,
  ADR-2605262130 + ADR-2605312345). LPU deterministic language-processing inference.

  Generated by 70-tools/scaffold_wave11_clj_datomic.py — replaces the Python main.py.
  CRUD + validation over a DI `DatomPort` seam (no external managed DB; the production
  adapter is kotoba-kqe, the test/browser adapter is `in-memory-datom`). No proprietary code."
  (:require [clojure.string :as str]))

;; ── Datomic-style schema (install via -transact) ──────────────────────────
(def schema
  "Attribute installs for this actor's entities (Datomic schema shape)."
  [;; LpuChip
   {:db/ident :groq_lpu.LpuChip/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :groq_lpu.LpuChip/name :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :groq_lpu.LpuChip/generation :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :groq_lpu.LpuChip/sramMb :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :groq_lpu.LpuChip/tflops :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :groq_lpu.LpuChip/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :groq_lpu.LpuChip/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; TensorStream
   {:db/ident :groq_lpu.TensorStream/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :groq_lpu.TensorStream/chipId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :groq_lpu.TensorStream/direction :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :groq_lpu.TensorStream/widthBytes :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :groq_lpu.TensorStream/throughputGbps :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :groq_lpu.TensorStream/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :groq_lpu.TensorStream/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; ScheduleSlot
   {:db/ident :groq_lpu.ScheduleSlot/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :groq_lpu.ScheduleSlot/chipId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :groq_lpu.ScheduleSlot/cycle :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :groq_lpu.ScheduleSlot/instruction :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :groq_lpu.ScheduleSlot/unit :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :groq_lpu.ScheduleSlot/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :groq_lpu.ScheduleSlot/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; Model
   {:db/ident :groq_lpu.Model/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :groq_lpu.Model/name :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :groq_lpu.Model/parameters :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :groq_lpu.Model/quantization :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :groq_lpu.Model/tokensPerSec :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :groq_lpu.Model/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :groq_lpu.Model/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; InterconnectLink
   {:db/ident :groq_lpu.InterconnectLink/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :groq_lpu.InterconnectLink/chipId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :groq_lpu.InterconnectLink/peerId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :groq_lpu.InterconnectLink/bandwidthGbps :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :groq_lpu.InterconnectLink/topology :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :groq_lpu.InterconnectLink/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :groq_lpu.InterconnectLink/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; InferenceJob
   {:db/ident :groq_lpu.InferenceJob/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :groq_lpu.InferenceJob/modelId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :groq_lpu.InferenceJob/chipId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :groq_lpu.InferenceJob/batchSize :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :groq_lpu.InferenceJob/status :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :groq_lpu.InferenceJob/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :groq_lpu.InferenceJob/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}])

(def entities #{"LpuChip" "TensorStream" "ScheduleSlot" "Model" "InterconnectLink" "InferenceJob"})

;; ── DatomPort — the DI seam to the kotoba Datom log ───────────────────────
(defprotocol DatomPort
  (-transact [this tx-data]
    "Append Datomic-shaped tx-data: entity maps {:db/id … attr v}, [:db/add e a v],
     [:db/retract e a v], [:db/retractEntity e].")
  (-pull [this eid]
    "Return the entity map for eid (incl. :db/id), or nil.")
  (-find-by-attr [this attr]
    "AEVT scan: the eids of every entity carrying attr."))

;; loud-failing default — a forgotten injection must never silently no-op
(defn unwired-datom []
  (reify DatomPort
    (-transact [_ _] (throw (ex-info "groq_lpu: DatomPort not wired — inject kotoba-kqe or in-memory-datom" {:unwired true})))
    (-pull [_ _] (throw (ex-info "groq_lpu: DatomPort not wired" {:unwired true})))
    (-find-by-attr [_ _] (throw (ex-info "groq_lpu: DatomPort not wired" {:unwired true})))))

;; in-memory fake — interprets the Datomic tx-data subset over {eid {attr v}}
(defn in-memory-datom []
  (let [store (atom {})]
    (reify DatomPort
      (-transact [_ tx-data]
        (doseq [op tx-data]
          (cond
            (map? op) (swap! store update (:db/id op) merge (dissoc op :db/id))
            (and (vector? op) (= :db/add (first op)))
            (let [[_ e a v] op] (swap! store assoc-in [e a] v))
            (and (vector? op) (= :db/retract (first op)))
            (let [[_ e a] op] (swap! store update e dissoc a))
            (and (vector? op) (= :db/retractEntity (first op)))
            (let [[_ e] op] (swap! store dissoc e))))
        {:db-after @store})
      (-pull [_ eid] (when-let [m (get @store eid)] (assoc m :db/id eid)))
      (-find-by-attr [_ attr] (vec (for [[eid m] @store :when (contains? m attr)] eid))))))

;; ── coercion (portable) ───────────────────────────────────────────────────
(defn- as-long [v]
  (cond (number? v) #?(:clj (long v) :cljs v)
        (string? v) (try #?(:clj (Long/parseLong (str/trim v))
                            :cljs (let [n (js/parseInt v 10)] (if (js/isNaN n) 0 n)))
                         (catch #?(:clj Exception :cljs :default) _ 0))
        :else 0))

(defn- as-double [v]
  (cond (number? v) #?(:clj (double v) :cljs v)
        (string? v) (try #?(:clj (Double/parseDouble (str/trim v))
                            :cljs (let [n (js/parseFloat v)] (if (js/isNaN n) 0.0 n)))
                         (catch #?(:clj Exception :cljs :default) _ 0.0))
        :else 0.0))

(defn- as-bool [v]
  (boolean (#{"1" "true" "yes" "on" true} (if (string? v) (str/lower-case v) v))))

(defn- now []
  #?(:clj (str (java.time.Instant/now)) :cljs (.toISOString (js/Date.))))

(defn- new-id [prefix]
  (str prefix "_" (subs (str/replace (str (random-uuid)) "-" "") 0 16)))

(defn- require-fields [data fields]
  (let [missing (remove (fn [k] (some? (get data (keyword k)))) fields)]
    (when (seq missing)
      (throw (ex-info (str "Missing required fields: " (str/join ", " missing))
                      {:type :invalid-request :missing (vec missing)})))))

;; ── list surface: filtering + cursor pagination (L4 parity) ───────────────
(def ^:const default-limit 20)
(def ^:const max-limit 100)

(defn- index-of [v x]
  (loop [i 0] (cond (>= i (count v)) -1 (= (nth v i) x) i :else (recur (inc i)))))

(defn- apply-filters
  "Keep rows matching every {attr v} in flt (string-compared), attr restricted to allowed."
  [rows flt allowed]
  (let [allowed (set allowed)]
    (reduce (fn [rs [a v]]
              (if (and (contains? allowed a) (some? v))
                (filterv (fn [r] (= (str (get r a)) (str v))) rs)
                rs))
            (vec rows) (or flt {}))))

(defn- paginate
  "Cursor pagination over rows → {:object :data :has-more :count :total}.
   opts {:limit N :starting-after <db/id>}."
  [rows opts]
  (let [limit (min (max (or (:limit opts) default-limit) 1) max-limit)
        start (:starting-after opts)
        rows  (vec rows)
        rows  (if start
                (let [idx (index-of (mapv :db/id rows) start)]
                  (if (neg? idx) rows (subvec rows (inc idx))))
                rows)
        page  (vec (take limit rows))]
    {:object "list" :data page :has-more (> (count rows) limit)
     :count (count page) :total (count rows)}))

;; ── LpuChip ────────────────────────────────────────────────────────────────
(defn create-lpu-chip
  "Create a LpuChip."
  [port data]
  (require-fields data ["name" "generation"])
  (let [id (new-id "lpu_lpu")
        e {:db/id id
           :groq_lpu.LpuChip/id id
           :groq_lpu.LpuChip/name (get data :name)
           :groq_lpu.LpuChip/generation (get data :generation)
           :groq_lpu.LpuChip/sramMb (as-long (get data :sramMb))
           :groq_lpu.LpuChip/tflops (as-double (get data :tflops))
           :groq_lpu.LpuChip/createdAt (now)
           :groq_lpu.LpuChip/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-lpu-chips
  "List LpuChip with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-lpu-chips port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :groq_lpu.LpuChip/id))
         rows (apply-filters rows (:filter opts) [:groq_lpu.LpuChip/name :groq_lpu.LpuChip/generation :groq_lpu.LpuChip/sramMb :groq_lpu.LpuChip/tflops])]
     (paginate rows opts))))

(defn get-lpu-chip
  "Retrieve a LpuChip by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-lpu-chip port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-lpu-chip
  "Update a LpuChip; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :name) (conj [:db/add id :groq_lpu.LpuChip/name (get data :name)]))
                   (cond-> (contains? data :generation) (conj [:db/add id :groq_lpu.LpuChip/generation (get data :generation)]))
                   (cond-> (contains? data :sramMb) (conj [:db/add id :groq_lpu.LpuChip/sramMb (as-long (get data :sramMb))]))
                   (cond-> (contains? data :tflops) (conj [:db/add id :groq_lpu.LpuChip/tflops (as-double (get data :tflops))]))
                   (conj [:db/add id :groq_lpu.LpuChip/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-lpu-chip
  "Delete a LpuChip."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── TensorStream ────────────────────────────────────────────────────────────────
(defn create-tensor-stream
  "Create a TensorStream."
  [port data]
  (require-fields data ["direction" "widthBytes"])
  (let [id (new-id "lpu_ten")
        e {:db/id id
           :groq_lpu.TensorStream/id id
           :groq_lpu.TensorStream/chipId (get data :chipId)
           :groq_lpu.TensorStream/direction (get data :direction)
           :groq_lpu.TensorStream/widthBytes (as-long (get data :widthBytes))
           :groq_lpu.TensorStream/throughputGbps (as-double (get data :throughputGbps))
           :groq_lpu.TensorStream/createdAt (now)
           :groq_lpu.TensorStream/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-tensor-streams
  "List TensorStream with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-tensor-streams port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :groq_lpu.TensorStream/id))
         rows (apply-filters rows (:filter opts) [:groq_lpu.TensorStream/chipId :groq_lpu.TensorStream/direction :groq_lpu.TensorStream/widthBytes :groq_lpu.TensorStream/throughputGbps])]
     (paginate rows opts))))

(defn get-tensor-stream
  "Retrieve a TensorStream by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-tensor-stream port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-tensor-stream
  "Update a TensorStream; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :chipId) (conj [:db/add id :groq_lpu.TensorStream/chipId (get data :chipId)]))
                   (cond-> (contains? data :direction) (conj [:db/add id :groq_lpu.TensorStream/direction (get data :direction)]))
                   (cond-> (contains? data :widthBytes) (conj [:db/add id :groq_lpu.TensorStream/widthBytes (as-long (get data :widthBytes))]))
                   (cond-> (contains? data :throughputGbps) (conj [:db/add id :groq_lpu.TensorStream/throughputGbps (as-double (get data :throughputGbps))]))
                   (conj [:db/add id :groq_lpu.TensorStream/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-tensor-stream
  "Delete a TensorStream."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── ScheduleSlot ────────────────────────────────────────────────────────────────
(defn create-schedule-slot
  "Create a ScheduleSlot."
  [port data]
  (require-fields data ["cycle" "instruction"])
  (let [id (new-id "lpu_sch")
        e {:db/id id
           :groq_lpu.ScheduleSlot/id id
           :groq_lpu.ScheduleSlot/chipId (get data :chipId)
           :groq_lpu.ScheduleSlot/cycle (as-long (get data :cycle))
           :groq_lpu.ScheduleSlot/instruction (get data :instruction)
           :groq_lpu.ScheduleSlot/unit (get data :unit)
           :groq_lpu.ScheduleSlot/createdAt (now)
           :groq_lpu.ScheduleSlot/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-schedule-slots
  "List ScheduleSlot with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-schedule-slots port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :groq_lpu.ScheduleSlot/id))
         rows (apply-filters rows (:filter opts) [:groq_lpu.ScheduleSlot/chipId :groq_lpu.ScheduleSlot/cycle :groq_lpu.ScheduleSlot/instruction :groq_lpu.ScheduleSlot/unit])]
     (paginate rows opts))))

(defn get-schedule-slot
  "Retrieve a ScheduleSlot by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-schedule-slot port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-schedule-slot
  "Update a ScheduleSlot; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :chipId) (conj [:db/add id :groq_lpu.ScheduleSlot/chipId (get data :chipId)]))
                   (cond-> (contains? data :cycle) (conj [:db/add id :groq_lpu.ScheduleSlot/cycle (as-long (get data :cycle))]))
                   (cond-> (contains? data :instruction) (conj [:db/add id :groq_lpu.ScheduleSlot/instruction (get data :instruction)]))
                   (cond-> (contains? data :unit) (conj [:db/add id :groq_lpu.ScheduleSlot/unit (get data :unit)]))
                   (conj [:db/add id :groq_lpu.ScheduleSlot/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-schedule-slot
  "Delete a ScheduleSlot."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── Model ────────────────────────────────────────────────────────────────
(defn create-model
  "Create a Model."
  [port data]
  (require-fields data ["name" "parameters"])
  (let [id (new-id "lpu_mod")
        e {:db/id id
           :groq_lpu.Model/id id
           :groq_lpu.Model/name (get data :name)
           :groq_lpu.Model/parameters (as-long (get data :parameters))
           :groq_lpu.Model/quantization (get data :quantization)
           :groq_lpu.Model/tokensPerSec (as-double (get data :tokensPerSec))
           :groq_lpu.Model/createdAt (now)
           :groq_lpu.Model/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-models
  "List Model with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-models port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :groq_lpu.Model/id))
         rows (apply-filters rows (:filter opts) [:groq_lpu.Model/name :groq_lpu.Model/parameters :groq_lpu.Model/quantization :groq_lpu.Model/tokensPerSec])]
     (paginate rows opts))))

(defn get-model
  "Retrieve a Model by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-model port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-model
  "Update a Model; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :name) (conj [:db/add id :groq_lpu.Model/name (get data :name)]))
                   (cond-> (contains? data :parameters) (conj [:db/add id :groq_lpu.Model/parameters (as-long (get data :parameters))]))
                   (cond-> (contains? data :quantization) (conj [:db/add id :groq_lpu.Model/quantization (get data :quantization)]))
                   (cond-> (contains? data :tokensPerSec) (conj [:db/add id :groq_lpu.Model/tokensPerSec (as-double (get data :tokensPerSec))]))
                   (conj [:db/add id :groq_lpu.Model/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-model
  "Delete a Model."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── InterconnectLink ────────────────────────────────────────────────────────────────
(defn create-interconnect-link
  "Create a InterconnectLink."
  [port data]
  (require-fields data ["bandwidthGbps" "topology"])
  (let [id (new-id "lpu_int")
        e {:db/id id
           :groq_lpu.InterconnectLink/id id
           :groq_lpu.InterconnectLink/chipId (get data :chipId)
           :groq_lpu.InterconnectLink/peerId (get data :peerId)
           :groq_lpu.InterconnectLink/bandwidthGbps (as-double (get data :bandwidthGbps))
           :groq_lpu.InterconnectLink/topology (get data :topology)
           :groq_lpu.InterconnectLink/createdAt (now)
           :groq_lpu.InterconnectLink/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-interconnect-links
  "List InterconnectLink with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-interconnect-links port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :groq_lpu.InterconnectLink/id))
         rows (apply-filters rows (:filter opts) [:groq_lpu.InterconnectLink/chipId :groq_lpu.InterconnectLink/peerId :groq_lpu.InterconnectLink/bandwidthGbps :groq_lpu.InterconnectLink/topology])]
     (paginate rows opts))))

(defn get-interconnect-link
  "Retrieve a InterconnectLink by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-interconnect-link port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-interconnect-link
  "Update a InterconnectLink; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :chipId) (conj [:db/add id :groq_lpu.InterconnectLink/chipId (get data :chipId)]))
                   (cond-> (contains? data :peerId) (conj [:db/add id :groq_lpu.InterconnectLink/peerId (get data :peerId)]))
                   (cond-> (contains? data :bandwidthGbps) (conj [:db/add id :groq_lpu.InterconnectLink/bandwidthGbps (as-double (get data :bandwidthGbps))]))
                   (cond-> (contains? data :topology) (conj [:db/add id :groq_lpu.InterconnectLink/topology (get data :topology)]))
                   (conj [:db/add id :groq_lpu.InterconnectLink/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-interconnect-link
  "Delete a InterconnectLink."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── InferenceJob ────────────────────────────────────────────────────────────────
(defn create-inference-job
  "Create a InferenceJob."
  [port data]
  (require-fields data ["batchSize" "status"])
  (let [id (new-id "lpu_inf")
        e {:db/id id
           :groq_lpu.InferenceJob/id id
           :groq_lpu.InferenceJob/modelId (get data :modelId)
           :groq_lpu.InferenceJob/chipId (get data :chipId)
           :groq_lpu.InferenceJob/batchSize (as-long (get data :batchSize))
           :groq_lpu.InferenceJob/status (get data :status)
           :groq_lpu.InferenceJob/createdAt (now)
           :groq_lpu.InferenceJob/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-inference-jobs
  "List InferenceJob with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-inference-jobs port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :groq_lpu.InferenceJob/id))
         rows (apply-filters rows (:filter opts) [:groq_lpu.InferenceJob/modelId :groq_lpu.InferenceJob/chipId :groq_lpu.InferenceJob/batchSize :groq_lpu.InferenceJob/status])]
     (paginate rows opts))))

(defn get-inference-job
  "Retrieve a InferenceJob by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-inference-job port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec
         (and want (contains? want :modelId) (get rec :groq_lpu.InferenceJob/modelId))
         (assoc :modelId-obj (-pull port (get rec :groq_lpu.InferenceJob/modelId))))))))

(defn update-inference-job
  "Update a InferenceJob; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :modelId) (conj [:db/add id :groq_lpu.InferenceJob/modelId (get data :modelId)]))
                   (cond-> (contains? data :chipId) (conj [:db/add id :groq_lpu.InferenceJob/chipId (get data :chipId)]))
                   (cond-> (contains? data :batchSize) (conj [:db/add id :groq_lpu.InferenceJob/batchSize (as-long (get data :batchSize))]))
                   (cond-> (contains? data :status) (conj [:db/add id :groq_lpu.InferenceJob/status (get data :status)]))
                   (conj [:db/add id :groq_lpu.InferenceJob/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-inference-job
  "Delete a InferenceJob."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── REST surface (host wires these to the kotoba-clj gateway) ──────────────
(def routes
  [{:method "POST" :path "/v1/lpuchips" :op :create :entity "LpuChip"}
   {:method "GET" :path "/v1/lpuchips" :op :list :entity "LpuChip"}
   {:method "GET" :path "/v1/lpuchips/:id" :op :get :entity "LpuChip"}
   {:method "PATCH" :path "/v1/lpuchips/:id" :op :update :entity "LpuChip"}
   {:method "DELETE" :path "/v1/lpuchips/:id" :op :delete :entity "LpuChip"}
   {:method "POST" :path "/v1/tensorstreams" :op :create :entity "TensorStream"}
   {:method "GET" :path "/v1/tensorstreams" :op :list :entity "TensorStream"}
   {:method "GET" :path "/v1/tensorstreams/:id" :op :get :entity "TensorStream"}
   {:method "PATCH" :path "/v1/tensorstreams/:id" :op :update :entity "TensorStream"}
   {:method "DELETE" :path "/v1/tensorstreams/:id" :op :delete :entity "TensorStream"}
   {:method "POST" :path "/v1/scheduleslots" :op :create :entity "ScheduleSlot"}
   {:method "GET" :path "/v1/scheduleslots" :op :list :entity "ScheduleSlot"}
   {:method "GET" :path "/v1/scheduleslots/:id" :op :get :entity "ScheduleSlot"}
   {:method "PATCH" :path "/v1/scheduleslots/:id" :op :update :entity "ScheduleSlot"}
   {:method "DELETE" :path "/v1/scheduleslots/:id" :op :delete :entity "ScheduleSlot"}
   {:method "POST" :path "/v1/models" :op :create :entity "Model"}
   {:method "GET" :path "/v1/models" :op :list :entity "Model"}
   {:method "GET" :path "/v1/models/:id" :op :get :entity "Model"}
   {:method "PATCH" :path "/v1/models/:id" :op :update :entity "Model"}
   {:method "DELETE" :path "/v1/models/:id" :op :delete :entity "Model"}
   {:method "POST" :path "/v1/interconnectlinks" :op :create :entity "InterconnectLink"}
   {:method "GET" :path "/v1/interconnectlinks" :op :list :entity "InterconnectLink"}
   {:method "GET" :path "/v1/interconnectlinks/:id" :op :get :entity "InterconnectLink"}
   {:method "PATCH" :path "/v1/interconnectlinks/:id" :op :update :entity "InterconnectLink"}
   {:method "DELETE" :path "/v1/interconnectlinks/:id" :op :delete :entity "InterconnectLink"}
   {:method "POST" :path "/v1/inferencejobs" :op :create :entity "InferenceJob"}
   {:method "GET" :path "/v1/inferencejobs" :op :list :entity "InferenceJob"}
   {:method "GET" :path "/v1/inferencejobs/:id" :op :get :entity "InferenceJob"}
   {:method "PATCH" :path "/v1/inferencejobs/:id" :op :update :entity "InferenceJob"}
   {:method "DELETE" :path "/v1/inferencejobs/:id" :op :delete :entity "InferenceJob"}])

;; collection → CRUD fns, keyed by the /v1/<collection> path segment
(def ^:private handlers
  {"lpuchips" {:create create-lpu-chip :list list-lpu-chips :get get-lpu-chip :update update-lpu-chip :delete delete-lpu-chip}
   "tensorstreams" {:create create-tensor-stream :list list-tensor-streams :get get-tensor-stream :update update-tensor-stream :delete delete-tensor-stream}
   "scheduleslots" {:create create-schedule-slot :list list-schedule-slots :get get-schedule-slot :update update-schedule-slot :delete delete-schedule-slot}
   "models" {:create create-model :list list-models :get get-model :update update-model :delete delete-model}
   "interconnectlinks" {:create create-interconnect-link :list list-interconnect-links :get get-interconnect-link :update update-interconnect-link :delete delete-interconnect-link}
   "inferencejobs" {:create create-inference-job :list list-inference-jobs :get get-inference-job :update update-inference-job :delete delete-inference-job}})

(defn- expand-opts [params]
  (when-let [x (:expand params)]
    {:expand (set (map keyword (str/split (str x) #",")))}))

(defn dispatch
  "Route an HTTP-ish request through `routes` to the CRUD fns.
   req: {:method (:get/:post/:patch/:delete) :path /v1/<coll>[/<id>] :params {} :body {}}.
   Returns {:status int :body any} — the runnable L4 service surface."
  [port {:keys [method path params body]}]
  (let [segs (->> (str/split (or path "") #"/") (remove str/blank?) vec)
        coll (get segs 1)
        id   (get segs 2)
        h    (get handlers coll)
        params (or params {})]
    (cond
      (nil? h) {:status 404 :body {:error "unknown collection"}}
      (and (= method :post) (nil? id)) {:status 201 :body ((:create h) port (or body params))}
      (and (= method :get) (nil? id)) {:status 200 :body ((:list h) port params)}
      (and (= method :get) id) (if-let [r ((:get h) port id (expand-opts params))]
                                 {:status 200 :body r} {:status 404 :body {:error "not found"}})
      (and (#{:patch :put} method) id) (if-let [r ((:update h) port id (or body params))]
                                         {:status 200 :body r} {:status 404 :body {:error "not found"}})
      (and (= method :delete) id) {:status 200 :body ((:delete h) port id)}
      :else {:status 405 :body {:error "method not allowed"}})))

(defn healthz []
  {:status "ok" :actor "groq_lpu-compat" :tier "L4"
   :lang "clojure" :persistence "datomic-eavt-kotoba"
   :entities entities})
