(ns groq_lpu.actor-test
  "Contract test for the groq_lpu-compat L4 actor (Clojure / kotoba-Datom).
  Runs on bb / clojure with classpath = src:tests. Generated by
  70-tools/scaffold_wave11_clj_datomic.py."
  (:require [clojure.test :refer [deftest is testing run-tests]]
            [clojure.string :as str]
            [groq_lpu.actor :as a]))

(def ENTITIES ["LpuChip" "TensorStream" "ScheduleSlot" "Model" "InterconnectLink" "InferenceJob"])

(deftest schema-has-all-entities
  (doseq [e ENTITIES]
    (is (some (fn [d] (str/starts-with? (str (:db/ident d)) (str ":groq_lpu." e "/"))) a/schema)
        (str "schema missing entity " e))))

(deftest entities-set-complete
  (is (= (set ENTITIES) a/entities)))

(deftest crud-roundtrip
  (testing "LpuChip create/get/list/update/delete over in-memory Datom log"
    (let [port (a/in-memory-datom)
          rec  (a/create-lpu-chip port {:name "x" :generation "x"})]
      (is (string? (:db/id rec)) "create returns a :db/id")
      (is (= rec (a/get-lpu-chip port (:db/id rec))) "get round-trips the record")
      (is (= 1 (:total (a/list-lpu-chips port))) "list total counts the created record")
      (let [up (a/update-lpu-chip port (:db/id rec) {:name "updated"})]
        (is (= "updated" (get up :groq_lpu.LpuChip/name)) "update applies the changed field"))
      (a/delete-lpu-chip port (:db/id rec))
      (is (= 0 (:total (a/list-lpu-chips port))) "delete removes the record"))))

(deftest list-filter-and-paginate
  (testing "L4 list surface: filtering + cursor pagination"
    (let [port (a/in-memory-datom)
          _ (a/create-lpu-chip port {:name "x" :generation "x"})
          _ (a/create-lpu-chip port {:name "y" :generation "x"})]
      (is (= 2 (:total (a/list-lpu-chips port))) "both records listed")
      (is (true? (:has-more (a/list-lpu-chips port {:limit 1}))) "limit drives has-more")
      (is (= 1 (:count (a/list-lpu-chips port {:limit 1}))) "limit caps the page")
      (is (= 1 (:total (a/list-lpu-chips port {:filter {:groq_lpu.LpuChip/name "x"}})))
          "filter narrows to the matching record"))))

(deftest validation-rejects-missing-required
  (is (thrown? #?(:clj clojure.lang.ExceptionInfo :cljs cljs.core/ExceptionInfo)
               (a/create-lpu-chip (a/in-memory-datom) {}))
      "create with no required fields throws"))

;; every entity collection (not just the first) → full lifecycle via dispatch
(def SAMPLES {"lpuchips" {:name "x" :generation "x"}
   "tensorstreams" {:direction "x" :widthBytes "x"}
   "scheduleslots" {:cycle "x" :instruction "x"}
   "models" {:name "x" :parameters "x"}
   "interconnectlinks" {:bandwidthGbps "x" :topology "x"}
   "inferencejobs" {:batchSize "x" :status "x"}})

(deftest all-collections-crud
  (testing "every entity collection runs the full lifecycle through dispatch"
    (doseq [[coll sample] SAMPLES]
      (let [port    (a/in-memory-datom)
            base    (str "/v1/" coll)
            created (a/dispatch port {:method :post :path base :body sample})
            id      (get-in created [:body :db/id])]
        (is (= 201 (:status created)) (str coll " POST → 201"))
        (is (string? id) (str coll " create body carries :db/id"))
        (is (= 200 (:status (a/dispatch port {:method :get :path (str base "/" id)})))
            (str coll " GET one → 200"))
        (is (= 1 (get-in (a/dispatch port {:method :get :path base}) [:body :total]))
            (str coll " list total 1"))
        (is (= 200 (:status (a/dispatch port {:method :delete :path (str base "/" id)})))
            (str coll " DELETE → 200"))
        (is (= 0 (get-in (a/dispatch port {:method :get :path base}) [:body :total]))
            (str coll " empty after delete"))))))

(deftest dispatch-end-to-end
  (testing "runnable service surface: create→get→list→update→delete through dispatch"
    (let [port (a/in-memory-datom)
          base "/v1/lpuchips"
          created (a/dispatch port {:method :post :path base :body {:name "x" :generation "x"}})
          id (get-in created [:body :db/id])]
      (is (= 201 (:status created)) "POST creates → 201")
      (is (string? id) "create body carries :db/id")
      (is (= 200 (:status (a/dispatch port {:method :get :path (str base "/" id)}))) "GET one → 200")
      (is (= 1 (get-in (a/dispatch port {:method :get :path base}) [:body :total])) "GET list → total 1")
      (is (= 404 (:status (a/dispatch port {:method :get :path (str base "/nope")}))) "GET absent → 404")
      (let [upd (a/dispatch port {:method :patch :path (str base "/" id) :body {:name "updated"}})]
        (is (= 200 (:status upd)) "PATCH → 200")
        (is (= "updated" (get-in upd [:body :groq_lpu.LpuChip/name])) "PATCH applies the field"))
      (is (= 200 (:status (a/dispatch port {:method :delete :path (str base "/" id)}))) "DELETE → 200")
      (is (= 0 (get-in (a/dispatch port {:method :get :path base}) [:body :total])) "list empty after delete")
      (is (= 404 (:status (a/dispatch port {:method :get :path "/v1/bogus"}))) "unknown collection → 404"))))

(deftest expand-inlines-relation
  (testing "?expand inlines the referenced Model on a InferenceJob"
    (let [port   (a/in-memory-datom)
          parent (a/create-model port {:name "x" :parameters "x"})
          child  (a/create-inference-job port (assoc {:batchSize "x" :status "x"} :modelId (:db/id parent)))
          got    (a/get-inference-job port (:db/id child) {:expand #{:modelId}})]
      (is (= (:db/id parent) (:db/id (:modelId-obj got)))
          "expand resolves the relation to the parent entity"))))

(defn -main [& _]
  (let [{:keys [fail error]} (run-tests 'groq_lpu.actor-test)]
    (System/exit (if (pos? (+ (or fail 0) (or error 0))) 1 0))))
